name: Build Docker image

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly trigger (adjust as needed)
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use GitHub Secrets for Docker credentials
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t zhouyut001/kcptube-docker:latest .  # Build the Docker image

      - name: Push Docker image
        run: |
          docker push zhouyut001/kcptube-docker:latest  # Push the image to Docker Hub
